# Character attribute pools for randomization/shuffling
# PURPOSE: Generate diverse characters to counter CivitAI model bias toward white subjects
# CRITICAL: Ensure ethnic, racial, and physical diversity in generated content

# Skin tones and ethnicity (PRIORITIZE DIVERSITY)
skin_tones:
  very_light:
    description: "Very pale, northern European"
    keywords: ["pale skin", "fair skin", "porcelain skin", "very light skin"]
    ethnicity_associations: ["scandinavian", "nordic", "irish", "british"]
    prompt_weight: 1.2
    probability: 0.15  # REDUCE to counter bias

  light:
    description: "Light skin, southern European/East Asian"
    keywords: ["light skin", "fair complexion", "light tone"]
    ethnicity_associations: ["italian", "spanish", "greek", "east asian", "korean", "japanese"]
    prompt_weight: 1.1
    probability: 0.15

  light_medium:
    description: "Light-medium, Mediterranean/Latin"
    keywords: ["light medium skin", "tan", "olive skin", "mediterranean skin"]
    ethnicity_associations: ["mediterranean", "middle eastern", "latina", "hispanic", "lebanese"]
    prompt_weight: 1.3
    probability: 0.20  # INCREASE diversity

  medium:
    description: "Medium skin, South Asian/Latin American"
    keywords: ["medium skin", "brown skin", "caramel skin", "warm skin tone"]
    ethnicity_associations: ["south asian", "indian", "pakistani", "brazilian", "mexican", "middle eastern"]
    prompt_weight: 1.4  # HIGHER weight to counter model bias
    probability: 0.20  # INCREASE diversity

  medium_dark:
    description: "Medium-dark, African/Afro-Latin"
    keywords: ["dark skin", "medium dark skin", "chocolate skin", "rich brown skin"]
    ethnicity_associations: ["african american", "black", "afro-latina", "caribbean", "african"]
    prompt_weight: 1.5  # MAXIMUM weight to counter strong bias
    probability: 0.15  # INCREASE diversity

  dark:
    description: "Dark skin, Sub-Saharan African"
    keywords: ["dark skin", "deep brown skin", "ebony skin", "dark complexion"]
    ethnicity_associations: ["african", "sub-saharan", "nigerian", "ethiopian", "kenyan"]
    prompt_weight: 1.6  # MAXIMUM weight needed
    probability: 0.15  # INCREASE diversity

# Explicit ethnicity keywords (use IN ADDITION to skin tone)
ethnicities:
  caucasian:
    keywords: ["european", "caucasian", "white"]
    prompt_weight: 1.0  # NO boost (already biased)
    probability: 0.15

  latina:
    keywords: ["latina", "hispanic", "latin american"]
    prompt_weight: 1.3
    probability: 0.15

  asian:
    keywords: ["asian", "east asian", "korean", "japanese", "chinese"]
    prompt_weight: 1.2
    probability: 0.15

  south_asian:
    keywords: ["south asian", "indian", "pakistani", "bengali"]
    prompt_weight: 1.4
    probability: 0.15

  middle_eastern:
    keywords: ["middle eastern", "arab", "persian", "lebanese"]
    prompt_weight: 1.3
    probability: 0.10

  black_african:
    keywords: ["black", "african", "african american", "afro"]
    prompt_weight: 1.5  # MAXIMUM
    probability: 0.15

  mixed_race:
    keywords: ["mixed race", "biracial", "multiracial"]
    prompt_weight: 1.3
    probability: 0.15

# Eye colors
eye_colors:
  brown:
    keywords: ["brown eyes", "dark eyes"]
    probability: 0.40  # Most common globally

  hazel:
    keywords: ["hazel eyes", "green-brown eyes"]
    probability: 0.15

  green:
    keywords: ["green eyes"]
    probability: 0.10

  blue:
    keywords: ["blue eyes"]
    probability: 0.15

  grey:
    keywords: ["grey eyes", "gray eyes"]
    probability: 0.05

  amber:
    keywords: ["amber eyes", "golden eyes"]
    probability: 0.05

  heterochromia:
    keywords: ["heterochromia", "different colored eyes"]
    probability: 0.02

  dark_brown:
    keywords: ["dark brown eyes", "almost black eyes"]
    probability: 0.08

# Hair colors (diverse)
hair_colors:
  black:
    keywords: ["black hair", "jet black hair"]
    probability: 0.35  # Most common globally

  dark_brown:
    keywords: ["dark brown hair", "brunette"]
    probability: 0.25

  brown:
    keywords: ["brown hair", "chestnut hair"]
    probability: 0.15

  light_brown:
    keywords: ["light brown hair", "light brunette"]
    probability: 0.08

  blonde:
    keywords: ["blonde hair", "golden hair"]
    probability: 0.08

  red:
    keywords: ["red hair", "ginger hair", "auburn hair"]
    probability: 0.03

  grey_silver:
    keywords: ["grey hair", "silver hair", "salt and pepper"]
    probability: 0.04  # For mature subjects

  white:
    keywords: ["white hair", "silver white hair"]
    probability: 0.02  # For elderly subjects

# Hair textures (CRITICAL for ethnic accuracy)
hair_textures:
  straight:
    keywords: ["straight hair", "sleek hair"]
    ethnicity_fit: ["asian", "caucasian"]
    probability: 0.30

  wavy:
    keywords: ["wavy hair", "loose waves"]
    ethnicity_fit: ["caucasian", "latina", "middle_eastern"]
    probability: 0.25

  curly:
    keywords: ["curly hair", "ringlets", "curls"]
    ethnicity_fit: ["latina", "middle_eastern", "mixed_race"]
    probability: 0.20

  coily_kinky:
    keywords: ["coily hair", "kinky hair", "afro textured", "type 4 hair"]
    ethnicity_fit: ["black_african", "african_american"]
    prompt_weight: 1.4  # HIGHER weight (often missed by models)
    probability: 0.15

  afro:
    keywords: ["afro", "natural afro", "big afro"]
    ethnicity_fit: ["black_african", "african_american"]
    prompt_weight: 1.5
    probability: 0.05

  braids:
    keywords: ["braids", "braided hair", "box braids", "cornrows"]
    ethnicity_fit: ["black_african", "african_american"]
    prompt_weight: 1.3
    probability: 0.05

# Body types (diverse)
body_types:
  petite:
    keywords: ["petite", "small frame", "delicate build"]
    probability: 0.15

  slim:
    keywords: ["slim", "slender", "lean"]
    probability: 0.20

  athletic:
    keywords: ["athletic", "toned", "fit", "muscular definition"]
    probability: 0.20

  average:
    keywords: ["average build", "normal physique"]
    probability: 0.15

  curvy:
    keywords: ["curvy", "voluptuous", "hourglass figure"]
    probability: 0.15

  plus_size:
    keywords: ["plus size", "full figured", "thick", "bbw"]
    probability: 0.10

  muscular:
    keywords: ["muscular", "buff", "strong physique"]
    probability: 0.05

# Breast sizes (explicit, diverse)
breast_sizes:
  small:
    keywords: ["small breasts", "petite breasts", "A cup", "B cup"]
    probability: 0.20

  medium:
    keywords: ["medium breasts", "average breasts", "C cup"]
    probability: 0.30

  large:
    keywords: ["large breasts", "big breasts", "D cup", "DD cup"]
    probability: 0.30

  very_large:
    keywords: ["very large breasts", "huge breasts", "E cup", "F cup"]
    probability: 0.15

  extra_large:
    keywords: ["extra large breasts", "massive breasts", "G+ cup"]
    probability: 0.05

# Age ranges (30+)
age_ranges:
  early_thirties:
    age_min: 30
    age_max: 34
    keywords: ["early 30s", "30 years old", "30-34"]
    probability: 0.25

  mid_thirties:
    age_min: 35
    age_max: 39
    keywords: ["mid 30s", "35 years old", "late 30s"]
    probability: 0.20

  forties:
    age_min: 40
    age_max: 49
    keywords: ["40s", "40 years old", "mature milf", "forties"]
    probability: 0.25

  fifties:
    age_min: 50
    age_max: 59
    keywords: ["50s", "50 years old", "mature", "fifties"]
    probability: 0.15

  sixties:
    age_min: 60
    age_max: 69
    keywords: ["60s", "60 years old", "senior", "sixties"]
    probability: 0.10

  seventies_plus:
    age_min: 70
    age_max: 85
    keywords: ["70s", "elderly", "senior", "grandmother age"]
    probability: 0.05

# Settings/locations
settings:
  bedroom:
    keywords: ["bedroom", "lying on bed", "bedroom setting"]
    lighting_suggestions: ["window light", "soft bedroom lighting"]
    probability: 0.25

  bathroom:
    keywords: ["bathroom", "shower", "bathtub", "bathroom setting"]
    lighting_suggestions: ["natural light", "bathroom lighting"]
    probability: 0.15

  living_room:
    keywords: ["living room", "couch", "sofa", "home interior"]
    lighting_suggestions: ["window light", "warm interior lighting"]
    probability: 0.15

  outdoor_beach:
    keywords: ["beach", "ocean", "sand", "seaside"]
    lighting_suggestions: ["golden hour", "natural sunlight"]
    probability: 0.10

  outdoor_nature:
    keywords: ["nature", "forest", "garden", "outdoor"]
    lighting_suggestions: ["natural light", "dappled sunlight"]
    probability: 0.10

  pool:
    keywords: ["pool", "swimming pool", "poolside"]
    lighting_suggestions: ["bright daylight", "pool lighting"]
    probability: 0.08

  studio:
    keywords: ["photo studio", "white background", "professional studio"]
    lighting_suggestions: ["studio lighting", "professional setup"]
    probability: 0.10

  hotel_room:
    keywords: ["hotel room", "luxury bedroom", "hotel setting"]
    lighting_suggestions: ["soft lighting", "ambient hotel light"]
    probability: 0.07

# Poses (diverse, explicit)
poses:
  standing:
    keywords: ["standing", "standing pose", "upright"]
    complexity: low
    probability: 0.15

  sitting:
    keywords: ["sitting", "seated", "sitting pose"]
    complexity: low
    probability: 0.15

  lying:
    keywords: ["lying down", "lying on bed", "reclined"]
    complexity: medium
    probability: 0.20

  kneeling:
    keywords: ["kneeling", "on knees", "kneeling pose"]
    complexity: medium
    probability: 0.10

  squatting:
    keywords: ["squatting", "squat pose", "crouching"]
    complexity: medium
    probability: 0.08

  legs_spread:
    keywords: ["legs spread", "legs apart", "open legs"]
    explicit: true
    complexity: medium
    probability: 0.12

  doggy_style:
    keywords: ["doggy style", "on all fours", "bent over"]
    explicit: true
    complexity: high
    probability: 0.08

  cowgirl:
    keywords: ["cowgirl position", "on top", "straddling"]
    explicit: true
    complexity: high
    probability: 0.07

  missionary:
    keywords: ["missionary position", "lying facing up"]
    explicit: true
    complexity: high
    probability: 0.05

# Randomization rules
randomization_rules:
  # CRITICAL: Skin tone and ethnicity must be consistent
  skin_ethnicity_consistency:
    enabled: true
    description: "Ensure skin tone matches ethnicity"

  # Hair texture must match ethnicity
  hair_texture_consistency:
    enabled: true
    description: "Match hair texture to ethnicity (e.g., coily hair for Black subjects)"

  # Age-appropriate features
  age_feature_consistency:
    enabled: true
    rules:
      - age_range: [30, 40]
        features: ["minimal age lines", "youthful mature"]
      - age_range: [40, 50]
        features: ["subtle age lines", "laugh lines"]
      - age_range: [50, 60]
        features: ["age lines", "mature features", "possible grey hair"]
      - age_range: [60, 100]
        features: ["prominent age lines", "grey or white hair", "senior features"]

  # Diversity targets (ENFORCE minimum representation)
  diversity_targets:
    min_non_white_percentage: 0.70  # 70% of generated characters should be non-white
    min_dark_skin_percentage: 0.30  # 30% should have medium-dark or dark skin
    description: "Counter CivitAI bias toward white subjects"
