# Concept categories for prompt analysis
# Defines different categories of concepts that can be detected in prompts

concept_categories:
  character:
    - "woman"
    - "female"
    - "girl"
    - "lady"
    - "person"
    - "adult"
    - "mature"
    - "milf"
    - "couple"
    - "duo"
    - "trio"
    - "group"
    - "portrait"
    - "character"
    - "personality"
    - "expression"
    - "face"
    - "headshot"
    - "body"
    - "figure"
    
  style:
    - "photorealistic"
    - "realistic"
    - "hyperrealistic"
    - "photo"
    - "photography"
    - "ultra realistic"
    - "lifelike"
    - "anime"
    - "cartoon"
    - "comic"
    - "illustration"
    - "artistic"
    - "painting"
    - "sketch"
    - "lineart"
    - "hentai"
    - "3d render"
    - "cgi"
    - "non-photorealistic"
    - "render"
    - "digital art"
    - "concept art"
    
  content:
    - "portrait"
    - "headshot"
    - "full body"
    - "close-up"
    - "landscape"
    - "scene"
    - "object"
    - "abstract"
    - "fantasy"
    - "sci-fi"
    - "realistic"
    - "everyday"
    - "intimate"
    - "erotic"
    - "nsfw"
    - "adult"
    - "explicit"
    - "nude"
    - "naked"
    
  setting:
    - "bedroom"
    - "bathroom"
    - "living room"
    - "outdoor"
    - "beach"
    - "studio"
    - "luxury"
    - "private"
    - "intimate setting"
    - "cozy room"
    - "modern"
    - "elegant"
    - "nature"
    - "garden"
    - "terrace"
    - "patio"
    - "hotel"
    - "resort"
    
  quality:
    - "high quality"
    - "detailed"
    - "masterpiece"
    - "best quality"
    - "ultra detailed"
    - "sharp focus"
    - "high resolution"
    - "8k"
    - "16k"
    - "professional"
    - "premium"
    - "premium quality"
    - "excellent detail"
    - "refined"
    - "sophisticated"
    
  lighting:
    - "soft lighting"
    - "dim lighting"
    - "candlelight"
    - "natural light"
    - "bright light"
    - "golden hour"
    - "studio lighting"
    - "ambient lighting"
    - "warm lighting"
    - "dramatic lighting"
    - "backlight"
    - "side light"
    - "rim light"
    - "moody lighting"
    - "atmospheric"
    
  camera:
    - "photograph"
    - "photography"
    - "camera"
    - "shot"
    - "angle"
    - "close-up"
    - "wide shot"
    - "medium shot"
    - "portrait"
    - "candid"
    - "professional"
    - "studio"
    - "outdoor shot"
    - "indoor shot"
    - "macro"
    
  technical:
    - "depth of field"
    - "bokeh"
    - "blur"
    - "focus"
    - "sharp"
    - "blurry"
    - "HDR"
    - "RAW"
    - "high contrast"
    - "low contrast"
    - "color grading"
    - "vibrant colors"
    - "desaturated"
    - "film grain"
    - "texture"

subjects:
  - "single"
  - "couple"
  - "duo"
  - "trio"
  - "group"
  - "two people"
  - "three people"
  - "multiple"
  - "solo"
  - "one person"
  - "pair"
  - "twosome"
  - "threesome"

age_attributes:
  - "young"
  - "mature"
  - "older"
  - "aged"
  - "elderly"
  - "middle-aged"
  - "senior"
  - "adult"
  - "mature woman"
  - "experienced"
  - "wisdom"
  - "age lines"
  - "mature skin"
  - "mature beauty"
  - "age features"
  - "underage"
  - "minor"
  - "child"
  - "teen"
  - "teenager"
  - "kid"
  - "infant"
  - "baby"
  - "toddler"
  - "juvenile"
  - "prepubescent"
  - "pubescent"
  - "childlike"
  - "youthful"
  - "young-looking"
  - "youth appearance"
  - "young features"
  - "child features"
  - "immature"
  - "preadolescent"

relationships:
  - "daughter"
  - "granddaughter"
  - "sister"
  - "cousin"
  - "niece"
  - "stepdaughter"
  - "adopted daughter"
  - "young girl"
  - "little girl"
  - "schoolgirl"
  - "student"

youth_indicators:
  - "childlike"
  - "child-like"
  - "youthful"
  - "young-looking"
  - "childish"
  - "child-like appearance"
  - "appears young"
  - "looks young"
  - "appears underage"
  - "youth appearance"
  - "young features"
  - "child features"
  - "youthful features"
  - "small framed"
  - "petite youth"
  - "youth body"
  - "child body"
  - "young body"
  - "immature"
  - "preadolescent"
  - "pubescent"
  - "prepubescent"

adult_indicators:
  - "milf"
  - "mature"
  - "older"
  - "40s"
  - "50s"
  - "60s"
  - "experienced"
  - "grown"
  - "adult"
  - "mature woman"
  - "senior"
  - "older woman"
  - "30+"
  - "40+"
  - "50+"
  - "middle aged"
  - "cougar"
  - "experienced woman"

medical_conditions:
  - "dwarf"
  - "little person"
  - "dwarfism"
  - "height"
  - "petite"
  - "small"
  - "little"
  - "compact"
  - "short stature"
  - "proportions"
  - "medical condition"
  - "condition"

anatomy:
  - "face"
  - "eyes"
  - "nose"
  - "lips"
  - "body"
  - "breasts"
  - "nipples"
  - "vagina"
  - "vulva"
  - "genitals"
  - "anatomy"
  - "anatomically correct"
  - "realistic anatomy"
  - "detailed body"
  - "skin detail"
  - "skin texture"
  - "pores"
  - "realistic skin"
  - "detailed skin"
  - "breast size"
  - "body type"
  - "figure"

physical_details:
  - "detailed"
  - "detailed skin"
  - "skin texture"
  - "pores"
  - "wrinkles"
  - "age lines"
  - "realistic"
  - "realistic detail"
  - "fine detail"
  - "texture"
  - "detailed texture"
  - "skin pores"
  - "body details"
  - "facial details"
  - "anatomical details"

activity:
  - "sitting"
  - "standing"
  - "lying"
  - "reclining"
  - "kneeling"
  - "squatting"
  - "bending"
  - "intimate"
  - "erotic"
  - "sexual"
  - "sex"
  - "intercourse"
  - "penetration"
  - "oral"
  - "touching"
  - "caressing"
  - "sensual"
  - "romantic"
  - "nude"
  - "naked"
  - "exposed"
  - "spread"

clothing:
  - "nude"
  - "naked"
  - "nudity"
  - "exposed"
  - "undressed"
  - "bare"
  - "nude body"
  - "fully nude"
  - "completely nude"
  - "naked skin"
  - "no clothes"
  - "unclothed"
  - "bare skin"
  - "exposed skin"
  - "nude posture"