# Generation profiles configuration
# Defines various profiles for different generation scenarios

age_profiles:
  young_adult:
    min_age: 18
    max_age: 25
    default_weight: 0.10
    probability: 0.1
    features: ["youthful skin", "minimal lines", "smooth skin", "bright expression"]
  
  adult:
    min_age: 26
    max_age: 39
    default_weight: 0.20
    probability: 0.25
    features: ["healthy skin", "mature beauty", "minimal age lines", "confident look"]
  
  milf:
    min_age: 40
    max_age: 54
    default_weight: 0.35
    probability: 0.40
    features: ["mature beauty", "subtle age lines", "experience", "confident look"]
  
  mature:
    min_age: 55
    max_age: 80
    default_weight: 0.25
    probability: 0.25
    features: ["wisdom lines", "mature features", "experienced look", "mature beauty"]

group_profiles:
  single:
    subjects: 1
    probability: 0.5
    default_resolution: [896, 1152]
    description: "Single person portrait"
  
  couple:
    subjects: 2
    probability: 0.3
    default_resolution: [1024, 1024]
    description: "Two people together"
  
  trio:
    subjects: 3
    probability: 0.15
    default_resolution: [1280, 896]
    description: "Three people together"
  
  group:
    subjects: 4
    probability: 0.05
    default_resolution: [1152, 896]
    description: "Four or more people"

activity_profiles:
  sitting:
    complexity: "low"
    default_steps: 25
    default_cfg: 9.0
    probability: 0.2
  
  standing:
    complexity: "low"
    default_steps: 25
    default_cfg: 9.0
    probability: 0.15
  
  kneeling:
    complexity: "medium"
    default_steps: 35
    default_cfg: 10.0
    probability: 0.15
  
  lying:
    complexity: "medium"
    default_steps: 35
    default_cfg: 10.0
    probability: 0.2
  
  intimate_close:
    complexity: "high"
    default_steps: 50
    default_cfg: 11.5
    probability: 0.15
  
  explicit_sexual:
    complexity: "high"
    default_steps: 60
    default_cfg: 12.5
    probability: 0.15

detail_presets:
  low:
    base_steps: 20
    base_cfg: 7.0
    base_resolution: [768, 768]
    description: "Quick generation with minimal detail"
  
  medium:
    base_steps: 35
    base_cfg: 9.0
    base_resolution: [1024, 1024]
    description: "Balanced quality and speed"
  
  high:
    base_steps: 50
    base_cfg: 11.0
    base_resolution: [1216, 832]
    description: "High quality with good detail"
  
  extreme:
    base_steps: 70
    base_cfg: 13.0
    base_resolution: [1536, 896]
    description: "Maximum detail and quality"

default_ranges:
  min_steps: 20
  max_steps: 80
  min_cfg: 7.0
  max_cfg: 15.0
  min_resolution: [768, 768]
  max_resolution: [1536, 1536]
  min_clip_skip: 1
  max_clip_skip: 12

vram_presets:
  low_vram:
    max_resolution: [768, 768]
    max_steps: 30
    max_cfg: 9.0
    estimated_vram: 6.0
    description: "Low VRAM usage, suitable for 8GB GPUs"
  
  medium_vram:
    max_resolution: [1024, 1024]
    max_steps: 50
    max_cfg: 11.0
    estimated_vram: 12.0
    description: "Balanced VRAM usage, suitable for 12GB GPUs"
  
  high_vram:
    max_resolution: [1216, 832]
    max_steps: 70
    max_cfg: 13.0
    estimated_vram: 16.0
    description: "High VRAM usage, suitable for 16GB+ GPUs"
  
  ultra_vram:
    max_resolution: [1536, 896]
    max_steps: 80
    max_cfg: 15.0
    estimated_vram: 24.0
    description: "Maximum VRAM usage, for high-end GPUs"