# Local ComfyUI models configuration
# Located in: /src/ComfyUI/models/
#
# PURPOSE: Map local models to use cases and diversity support
# SCANNED: 44 checkpoints, 1206 LoRAs

# Primary photorealistic checkpoints (RECOMMENDED)
primary_checkpoints:
  # Ultra-realistic general purpose
  pornmaster_proSDXLV7:
    path: "/src/ComfyUI/models/checkpoints/pornmaster_proSDXLV7.safetensors"
    type: "SDXL"
    specialty: "Explicit adult content, professional quality"
    diversity_support: "good"  # Test needed
    recommended_cfg: [9.0, 12.0]
    recommended_steps: [35, 60]
    notes: "Likely best for explicit adult scenes"

  epicphotogasm_ultimateFidelity:
    path: "/src/ComfyUI/models/checkpoints/epicphotogasm_ultimateFidelity.safetensors"
    type: "SDXL"
    specialty: "Ultra-realistic photography"
    diversity_support: "medium"
    recommended_cfg: [8.0, 11.0]
    recommended_steps: [30, 50]

  realismByStableYogi_v5XLFP16:
    path: "/src/ComfyUI/models/checkpoints/realismByStableYogi_v5XLFP16.safetensors"
    type: "SDXL"
    specialty: "Photorealistic portraits"
    diversity_support: "medium"
    recommended_cfg: [8.0, 10.0]
    recommended_steps: [30, 45]

  cyberrealisticXL_v60:
    path: "/src/ComfyUI/models/checkpoints/cyberrealisticXL_v60.safetensors"
    type: "SDXL"
    specialty: "Realistic with slight artistic enhancement"
    diversity_support: "good"
    recommended_cfg: [7.5, 10.0]
    recommended_steps: [30, 50]

  sdxlbaseNsfwFaces_sdxlNsfwFaces02:
    path: "/src/ComfyUI/models/checkpoints/sdxlbaseNsfwFaces_sdxlNsfwFaces02.safetensors"
    type: "SDXL"
    specialty: "NSFW faces, detailed facial features"
    diversity_support: "unknown"  # Test needed
    recommended_cfg: [9.0, 12.0]
    recommended_steps: [35, 55]
    notes: "Good for close-up face detail in explicit content"

  sensuaxlV2_v20:
    path: "/src/ComfyUI/models/checkpoints/sensuaxlV2_v20.safetensors"
    type: "SDXL"
    specialty: "Sensual/erotic content"
    diversity_support: "medium"
    recommended_cfg: [8.0, 11.0]
    recommended_steps: [35, 55]

# Age/body-specific checkpoints
specialty_checkpoints:
  naturalBeautiesPHOTO_nbPHOTO250629:
    path: "/src/ComfyUI/models/checkpoints/naturalBeautiesPHOTO_nbPHOTO250629.safetensors"
    type: "SDXL"
    specialty: "Natural beauty, realistic women"
    use_for_ages: [30, 60]
    diversity_support: "good"
    recommended_cfg: [8.0, 10.5]
    notes: "Good for mature women with natural features"

  naturalBeautiesREAL_nbREAL250629:
    path: "/src/ComfyUI/models/checkpoints/naturalBeautiesREAL_nbREAL250629.safetensors"
    type: "SDXL"
    specialty: "Ultra-realistic natural beauty"
    use_for_ages: [30, 70]
    diversity_support: "good"
    recommended_cfg: [8.5, 11.0]
    notes: "Excellent for mature/senior women"

  babesByStableYogiSDXL_v50FP16:
    path: "/src/ComfyUI/models/checkpoints/babesByStableYogiSDXL_v50FP16.safetensors"
    type: "SDXL"
    specialty: "Attractive women, glamour"
    use_for_ages: [25, 45]
    diversity_support: "medium"
    notes: "May skew younger, use with age weighting"

  bbwFantasy_v10:
    path: "/src/ComfyUI/models/checkpoints/bbwFantasy_v10.safetensors"
    type: "SD1.5"  # Smaller file
    specialty: "Plus-size women, BBW"
    body_types: ["plus_size", "curvy"]
    diversity_support: "unknown"
    recommended_cfg: [7.0, 9.0]
    notes: "Specialized for larger body types"

  bigasp_v20:
    path: "/src/ComfyUI/models/checkpoints/bigasp_v20.safetensors"
    type: "SDXL"
    specialty: "Posterior focus, explicit anatomy"
    anatomical_focus: ["buttocks", "hips", "rear"]
    diversity_support: "unknown"
    recommended_cfg: [9.0, 12.0]
    notes: "Use for posterior-focused explicit scenes"

# Pony-based (TEST for photorealism)
pony_checkpoints:
  ponyRealism_V23ULTRA:
    path: "/src/ComfyUI/models/checkpoints/ponyRealism_V23ULTRA.safetensors"
    type: "Pony Diffusion"
    specialty: "Pony-based photorealism attempt"
    diversity_support: "unknown"
    notes: "TEST ONLY - Pony models may not achieve true photorealism"
    recommended: false  # Prefer pure SDXL for photorealism

# AVOID (cartoon/anime/illustration)
blocked_checkpoints:
  - "bubbliCartoonIL_v10"  # Cartoon
  # Add others as discovered

# Model selection strategy
selection_strategy:
  # Primary model selection based on use case
  default_explicit: "pornmaster_proSDXLV7"
  default_portrait: "naturalBeautiesREAL_nbREAL250629"
  default_body_focus: "epicphotogasm_ultimateFidelity"

  # Age-based preferences
  age_30_40: "sensuaxlV2_v20"
  age_40_50: "naturalBeautiesPHOTO_nbPHOTO250629"
  age_50_60: "naturalBeautiesREAL_nbREAL250629"
  age_60_plus: "naturalBeautiesREAL_nbREAL250629"

  # Body type preferences
  plus_size: "bbwFantasy_v10"
  athletic: "epicphotogasm_ultimateFidelity"
  curvy: "sensuaxlV2_v20"

  # Ethnicity/diversity preferences
  # NOTE: All models likely biased toward white subjects
  # Use HIGH prompt weighting (1.4-1.6) for non-white ethnicities
  non_white_ethnicity:
    primary: "realismByStableYogi_v5XLFP16"  # Generally good at diversity
    alternative: "cyberrealisticXL_v60"
    prompt_weight_boost: 0.3  # Add +0.3 to base weight

# LoRA categories (based on observed files)
lora_categories:
  clothing:
    examples:
      - "0584 black lace underwear_v1_pony"
      - "0453 Lace gelcoat nun_v1_pony"
    notes: "Many Pony-based, may need testing for photorealism"

  activities:
    examples:
      - "0654 bdsm_v1_pony"
      - "0592 female ejaculation_v1_pony"
    notes: "Explicit activity LoRAs, Pony-based"

  styles:
    notes: "Many stylized/fantasy LoRAs - AVOID for photorealism"

  anatomy:
    notes: "Look for LoRAs with 'realistic anatomy', 'skin detail', 'pores'"

# Testing priorities
testing_needed:
  diversity_tests:
    description: "Test models with non-white ethnicities"
    models_to_test:
      - "pornmaster_proSDXLV7"
      - "realismByStableYogi_v5XLFP16"
      - "naturalBeautiesREAL_nbREAL250629"
      - "cyberrealisticXL_v60"
    test_prompts:
      - "(40 years old:1.2), (african american:1.5), (dark skin:1.5), (black woman:1.4)"
      - "(mature milf:1.2), (south asian:1.4), (medium brown skin:1.4), (indian:1.3)"
      - "(50 years old:1.2), (latina:1.3), (medium skin:1.3), (hispanic:1.3)"

  age_accuracy_tests:
    description: "Test age rendering accuracy"
    models_to_test:
      - "naturalBeautiesREAL_nbREAL250629"
      - "naturalBeautiesPHOTO_nbPHOTO250629"
    test_prompts:
      - "(60 years old:1.3), (senior:1.3), (grey hair:1.2), (age lines:1.2)"
      - "(55 years old:1.3), (mature:1.3), (natural aging:1.2)"

# Recommended workflow
recommended_workflow:
  step1_character_generation:
    tool: "CharacterGenerator"
    output: "Character with ethnicity, age, body type, etc."

  step2_model_selection:
    tool: "ModelSelector (to be created)"
    logic: "Select checkpoint based on character attributes"
    example: "60y latina → naturalBeautiesREAL_nbREAL250629"

  step3_lora_selection:
    tool: "LoRARecommender (existing, enhanced)"
    logic: "Select LoRAs for anatomy, clothing, activity"
    filters: "BLOCK Pony LoRAs if checkpoint is SDXL"

  step4_parameter_optimization:
    tool: "ParameterOptimizer (existing)"
    inputs: "Character + Model"
    output: "CFG, steps, resolution, sampler"

  step5_prompt_construction:
    tool: "PromptBuilder (to be created)"
    logic: "Combine character prompt + quality keywords + negative prompt"
    weighting: "Apply ethnic/age weighting from character"
