# LoRA filters configuration
# Defines tags and settings for LoRA recommendation filtering

blocked_tags:
  - "anime"
  - "cartoon"
  - "comic"
  - "illustration"
  - "drawn"
  - "animated"
  - "cel shaded"
  - "2d"
  - "manga"
  - "stylized"
  - "artistic"
  - "painting"
  - "sketch"
  - "lineart"
  - "hentai"
  - "3d render"
  - "cgi"
  - "non-photorealistic"
  - "teen"
  - "young"
  - "loli"
  - "shota"
  - "child"
  - "minor"
  - "18"
  - "19"
  - "20s"
  - "twenties"
  - "underage"
  - "under age"
  - "under_age"
  - "young adult"
  - "daughter"
  - "granddaughter"
  - "sister"
  - "cousin"
  - "niece"
  - "stepdaughter"
  - "adopted daughter"
  - "young girl"
  - "little girl"
  - "schoolgirl"
  - "student"
  - "under 18"
  - "under-eighteen"
  - "below 18"
  - "below-eighteen"
  - "juvenile"
  - "youth"
  - "underaged"
  - "prepubescent"
  - "pubescent"
  - "teenager"
  - "toddler"
  - "infant"
  - "baby"
  - "childlike"
  - "child-like"
  - "youthful"
  - "young-looking"
  - "childish"
  - "child-like appearance"
  - "appears young"
  - "looks young"
  - "appears underage"
  - "youth appearance"
  - "young features"
  - "child features"
  - "youthful features"
  - "small framed"
  - "petite youth"
  - "youth body"
  - "child body"
  - "young body"

priority_tags:
  # Realism
  - "photorealistic"
  - "realistic"
  - "photo"
  - "photography"
  - "hyperrealistic"
  - "ultra realistic"
  - "lifelike"
  - "natural"
  - "real"
  - "life like"

  # Adult content
  - "nsfw"
  - "adult"
  - "explicit"
  - "nude"
  - "naked"
  - "erotic"
  - "sexual"
  - "porn"
  - "xxx"
  - "mature content"
  - "intimate"

  # Age appropriateness (30+)
  - "milf"
  - "mature"
  - "30+"
  - "40+"
  - "50+"
  - "60+"
  - "older woman"
  - "experienced"
  - "cougar"
  - "older"
  - "senior"
  - "mature woman"

  # Body types and features
  - "anatomy"
  - "realistic anatomy"
  - "detailed body"
  - "skin detail"
  - "skin texture"
  - "pores"
  - "body"
  - "figure"
  - "body type"
  - "anatomically correct"
  - "detailed skin"
  - "realistic skin"

  # Quality
  - "professional"
  - "high quality"
  - "detailed"
  - "8k"
  - "16k"
  - "masterpiece"
  - "best quality"
  - "ultra detailed"
  - "sharp focus"
  - "premium"
  - "premium quality"

anatomy_tags:
  - "breasts"
  - "nipples"
  - "anatomy"
  - "body"
  - "vagina"
  - "vulva"
  - "genitals"
  - "intimate"
  - "realistic skin"
  - "skin detail"
  - "pores"
  - "realistic body"
  - "anatomically correct"
  - "body type"
  - "body shape"
  - "figure"
  - "detailed body"
  - "anatomical details"
  - "body details"

scoring_weights:
  priority_score_weight: 0.25
  anatomy_score_weight: 0.20
  keyword_score_weight: 0.25
  tag_score_weight: 0.20
  popularity_score_weight: 0.10

lora_limits:
  max_loras: 3
  min_confidence: 0.5
  max_total_weight: 3.0
  max_individual_weight: 1.2
  min_individual_weight: 0.3