# Prompting strategies configuration
# Defines various strategies for prompt optimization

prompt_structure:
  order: ["age", "ethnicity", "skin_tone", "eye_color", "hair", "body", "breast_size", "pose", "setting", "lighting"]
  required_sections: ["ethnicity", "skin_tone", "age"]
  optional_sections: ["pose", "setting", "lighting", "accessories"]
  weight_rules:
    ethnicity_weight: 1.0
    skin_tone_weight: 1.2
    age_weight: 1.2
    explicit_pose_weight: 1.3
    hair_texture_weight: 1.1

model_strategies:
  sdxl:
    default_sampler: "DPM++ 2M Karras"
    default_clip_skip: 1
    resolution_preference: "landscape"
    steps_multiplier: 1.0
    cfg_multiplier: 1.0
  
  sd20:
    default_sampler: "Euler A"
    default_clip_skip: 2
    resolution_preference: "square"
    steps_multiplier: 0.9
    cfg_multiplier: 0.95
  
  sd15:
    default_sampler: "Euler"
    default_clip_skip: 2
    resolution_preference: "square"
    steps_multiplier: 0.8
    cfg_multiplier: 0.9
  
  pony:
    default_sampler: "DPM++ 2M Karras"
    default_clip_skip: 1
    resolution_preference: "portrait"
    steps_multiplier: 1.1
    cfg_multiplier: 1.05

negative_prompts:
  photorealistic:
    - "anime"
    - "cartoon"
    - "comic"
    - "illustration"
    - "drawing"
    - "painting"
    - "sketch"
    - "render"
    - "3d"
    - "stylized"
    - "cartoonish"
    - "manga"
    - "hentai"
    - "low quality"
    - "blurry"
    - "ugly"
    - "deformed"
    - "bad anatomy"
    - "extra limbs"
    - "missing limbs"
    - "bad hands"
    - "bad feet"
    - "bad face"
    - "extra eyes"
    - "extra mouth"
    - "mutation"
    - "mutated"
    - "disfigured"

  explicit:
    - "clothed"
    - "fully clothed"
    - "covered"
    - "conservative"
    - "modest"
    - "innocent"
    - "pure"
    - "chaste"
    - "virginal"
    - "covered up"
    - "fully dressed"
    - "dressed"
    - "clothing"
    - "apparel"
    - "garments"

  age_inappropriate:
    - "child"
    - "minor"
    - "underage"
    - "young"
    - "teenager"
    - "18"
    - "19"
    - "20"
    - "baby"
    - "infant"
    - "kid"
    - "toddler"
    - "young looking"
    - "juvenille"
    - "prepubescent"
    - "pubescent"
    - "daughter"
    - "granddaughter"
    - "sister"
    - "cousin"
    - "niece"
    - "stepdaughter"
    - "adopted daughter"
    - "young girl"
    - "little girl"
    - "schoolgirl"
    - "student"
    - "under 18"
    - "under-eighteen"
    - "below 18"
    - "below-eighteen"
    - "juvenile"
    - "youth"
    - "underaged"
    - "childlike"
    - "youthful"
    - "child-like"
    - "childish"
    - "child-like appearance"
    - "appears young"
    - "looks young"
    - "appears underage"
    - "youth appearance"
    - "young features"
    - "child features"
    - "youthful features"
    - "small framed"
    - "youth body"
    - "child body"
    - "young body"
    - "immature"
    - "preadolescent"