# Example fact types configuration for Law discipline

discipline: law
fact_types:
  - id: law.jurisdiction_level
    discipline: law
    required: true
    constraints:
      - kind: ALLOWED_SET
        values: ["local", "regional", "national", "international"]
  - id: law.regulation_type
    discipline: law
    required: false
    constraints:
      - kind: ALLOWED_SET
        values: ["law", "regulation", "directive", "ordinance"]
  - id: law.legal_status
    discipline: law
    required: false
    constraints: []
  - id: law.compliance_rate
    discipline: law
    required: false
    constraints: []
