"""Agent message type enumeration."""

from enum import Enum


class AgentMessageType(Enum):
    """Types of messages agents can send to each other."""

    QUESTION = "QUESTION"
    RESPONSE = "RESPONSE"
    REQUEST_COLLABORATION = "REQUEST_COLLABORATION"
    ACCEPT_COLLABORATION = "ACCEPT_COLLABORATION"
    DECLINE_COLLABORATION = "DECLINE_COLLABORATION"
    SHARE_FINDING = "SHARE_FINDING"
    CHALLENGE_ASSUMPTION = "CHALLENGE_ASSUMPTION"
    PROVIDE_CONTEXT = "PROVIDE_CONTEXT"
    REQUEST_REVIEW = "REQUEST_REVIEW"
    ACKNOWLEDGE = "ACKNOWLEDGE"
